### ISSUE TITLE
Does this module prevent other apps from being able to scan for Wi-Fi networks in the background?

### ISSUE THREAD

**Issue by ArtificialTruth** [mtgrosser/DenyLocationConsent#10]
When Scanning Always Available is enabled, (and location) apps can scan for Wi-Fi networks in the background, and this data is being sent to Google.
Does this module prevent data from being sent to Google, but still allow apps to scan for Wi-Fi networks in the background, (and don't disable the Scanning Always Available setting)?

Pic of the Scanning Always Available setting:
![Scanning Always Available setting](http://www.howtogeek.com/wp-content/uploads/2015/03/ximg_54f7b31055413.png.pagespeed.gp+jp+jw+pj+js+rj+rp+rw+ri+cp+md.ic.WJDdVea8nw.png)

**Comment by mtgrosser** [comment]
The module only hooks into NetworkLocation(Chimera)Service and always disagrees to the consent dialog.

**Comment by ArtificialTruth** [comment]
Thank you for the answer.
