### ISSUE TITLE
Version that always agrees?

### ISSUE THREAD

**Issue by stevedensmore** [mtgrosser/DenyLocationConsent#11]
Could you please make a version of this that agrees?  The other module you based yours off of is no longer functional.  Please and thank you!

**Comment by godzellax** [comment]
Yes please I need it to auto agree. Maybe make an option to choose between auto agree or disagree will be the best app.

**Comment by kurokirasama** [comment]
Yes!!! I need this version too please!

**Comment by mtgrosser** [comment]
Feel free to create such a module, after all this is open source software. 
Looking at the gms code, I consider it malevolent. Therefore, I won't.
